version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RUN_STAGE=dev
      - PORT=8000
      - WORKERS=4
    volumes:
      - ./api:/app/api
      - ./utils:/app/utils
      - ./review_scripts:/app/review_scripts
 
    restart: unless-stopped