version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RUN_STAGE=prod
      - PORT=8000
      - WORKERS=4
    volumes:
      - ./.env:/app/.env
      - ./admin-10ac-service.json:/app/admin-10ac-service.json
    restart: unless-stopped